export const LEARNING_TRACKS = {
  QA: {
    value: 'QA',
    label: 'QA',
    title: 'QA Fellowship Track',
    quizPath: '/quizzes/qa',
    quizSlug: 'qa',
    categoryKeywords: ['qa', 'quality'],
    description: 'Practice testing foundations, quality process, and tools.',
    skills: ['Manual testing', 'Bug reporting', 'Test cases', 'QA process'],
    pathLabel: 'Beginner Friendly',
  },
  SALESFORCE: {
    value: 'SALESFORCE',
    label: 'Salesforce',
    title: 'Salesforce Fellowship Track',
    quizPath: '/quizzes/salesforce',
    quizSlug: 'salesforce',
    categoryKeywords: ['salesforce'],
    description: 'Build confidence with CRM concepts and platform workflows.',
    skills: ['CRM basics', 'Objects', 'Automation', 'Admin workflows'],
    pathLabel: 'CRM Track',
  },
  AWS_PRACTITIONER: {
    value: 'AWS_PRACTITIONER',
    label: 'AWS Practitioner',
    title: 'AWS Practitioner Track',
    quizPath: '/quizzes/aws-practitioner',
    quizSlug: 'aws-practitioner',
    categoryKeywords: ['aws practitioner', 'practitioner'],
    description: 'Review core cloud, pricing, support, and security concepts.',
    skills: ['Cloud basics', 'Billing', 'Security', 'AWS services'],
    pathLabel: 'Cloud Track',
  },
  AWS_ARCHITECT: {
    value: 'AWS_ARCHITECT',
    label: 'AWS Architect',
    title: 'AWS Architect Track',
    quizPath: '/quizzes/aws-architect',
    quizSlug: 'aws-architect',
    categoryKeywords: ['aws architect', 'architect'],
    description: 'Prepare for architecture patterns and cloud design choices.',
    skills: ['Architecture', 'Networking', 'Resilience', 'Design patterns'],
    pathLabel: 'Advanced Cloud Track',
  },
}

export const LEARNING_TRACK_OPTIONS = Object.values(LEARNING_TRACKS)
