from app.models.assignment_model import AssignmentStatus
from app.models.submission_model import SubmissionStatus


ASSIGNMENT_STATUS_DRAFT = "draft"
ASSIGNMENT_STATUS_PUBLISHED = "published"
ASSIGNMENT_STATUS_ARCHIVED = "archived"

ASSIGNMENT_STATUS_VALUES = {
    ASSIGNMENT_STATUS_DRAFT,
    ASSIGNMENT_STATUS_PUBLISHED,
    ASSIGNMENT_STATUS_ARCHIVED,
}

ASSIGNMENT_STATUS_TO_MODEL = {
    ASSIGNMENT_STATUS_DRAFT: AssignmentStatus.DRAFT,
    ASSIGNMENT_STATUS_PUBLISHED: AssignmentStatus.PUBLISHED,
    ASSIGNMENT_STATUS_ARCHIVED: AssignmentStatus.ARCHIVED,
}

MODEL_ASSIGNMENT_STATUS_TO_API = {
    AssignmentStatus.DRAFT: ASSIGNMENT_STATUS_DRAFT,
    AssignmentStatus.OPEN: ASSIGNMENT_STATUS_PUBLISHED,
    AssignmentStatus.CLOSED: ASSIGNMENT_STATUS_ARCHIVED,
    AssignmentStatus.PUBLISHED: ASSIGNMENT_STATUS_PUBLISHED,
    AssignmentStatus.ARCHIVED: ASSIGNMENT_STATUS_ARCHIVED,
}

SUBMISSION_TYPE_VALUES = {
    "text",
    "link",
    "file-link",
    "github-link",
    "mixed",
}

SUBMISSION_STATUS_NOT_SUBMITTED = "not-submitted"
SUBMISSION_STATUS_SUBMITTED = "submitted"
SUBMISSION_STATUS_UNDER_REVIEW = "under-review"
SUBMISSION_STATUS_REVIEWED = "reviewed"
SUBMISSION_STATUS_NEEDS_RESUBMISSION = "needs-resubmission"

SUBMISSION_STATUS_VALUES = {
    SUBMISSION_STATUS_NOT_SUBMITTED,
    SUBMISSION_STATUS_SUBMITTED,
    SUBMISSION_STATUS_UNDER_REVIEW,
    SUBMISSION_STATUS_REVIEWED,
    SUBMISSION_STATUS_NEEDS_RESUBMISSION,
}

SUBMISSION_STATUS_TO_MODEL = {
    SUBMISSION_STATUS_SUBMITTED: SubmissionStatus.SUBMITTED_V2,
    SUBMISSION_STATUS_UNDER_REVIEW: SubmissionStatus.UNDER_REVIEW,
    SUBMISSION_STATUS_REVIEWED: SubmissionStatus.REVIEWED_V2,
    SUBMISSION_STATUS_NEEDS_RESUBMISSION: SubmissionStatus.NEEDS_RESUBMISSION,
}

MODEL_SUBMISSION_STATUS_TO_API = {
    SubmissionStatus.NOT_SUBMITTED: SUBMISSION_STATUS_NOT_SUBMITTED,
    SubmissionStatus.SUBMITTED: SUBMISSION_STATUS_SUBMITTED,
    SubmissionStatus.SUBMITTED_V2: SUBMISSION_STATUS_SUBMITTED,
    SubmissionStatus.UNDER_REVIEW: SUBMISSION_STATUS_UNDER_REVIEW,
    SubmissionStatus.REVIEWED: SUBMISSION_STATUS_REVIEWED,
    SubmissionStatus.REVIEWED_V2: SUBMISSION_STATUS_REVIEWED,
    SubmissionStatus.NEEDS_REVISION: SUBMISSION_STATUS_NEEDS_RESUBMISSION,
    SubmissionStatus.NEEDS_RESUBMISSION: SUBMISSION_STATUS_NEEDS_RESUBMISSION,
}
