from app.models.user_model import LearningTrack


SELECTED_TRACK_QA = "qa"
SELECTED_TRACK_AWS_PRACTITIONER = "aws-practitioner"
SELECTED_TRACK_AWS_ARCHITECT = "aws-architect"
SELECTED_TRACK_SALESFORCE = "salesforce"

SELECTED_TRACK_VALUES = {
    SELECTED_TRACK_QA,
    SELECTED_TRACK_AWS_PRACTITIONER,
    SELECTED_TRACK_AWS_ARCHITECT,
    SELECTED_TRACK_SALESFORCE,
}

LEARNING_TRACK_TO_SELECTED_TRACK = {
    LearningTrack.QA: SELECTED_TRACK_QA,
    LearningTrack.AWS_PRACTITIONER: SELECTED_TRACK_AWS_PRACTITIONER,
    LearningTrack.AWS_ARCHITECT: SELECTED_TRACK_AWS_ARCHITECT,
    LearningTrack.SALESFORCE: SELECTED_TRACK_SALESFORCE,
}

SELECTED_TRACK_TO_LEARNING_TRACK = {
    selected_track: learning_track
    for learning_track, selected_track in LEARNING_TRACK_TO_SELECTED_TRACK.items()
}
