SESSION_STATUS_SCHEDULED = "scheduled"
SESSION_STATUS_COMPLETED = "completed"
SESSION_STATUS_CANCELLED = "cancelled"
SESSION_STATUS_ARCHIVED = "archived"

SESSION_STATUS_VALUES = {
    SESSION_STATUS_SCHEDULED,
    SESSION_STATUS_COMPLETED,
    SESSION_STATUS_CANCELLED,
    SESSION_STATUS_ARCHIVED,
}

ATTENDANCE_STATUS_NOT_MARKED = "not-marked"
ATTENDANCE_STATUS_PRESENT = "present"
ATTENDANCE_STATUS_ABSENT = "absent"
ATTENDANCE_STATUS_LATE = "late"
ATTENDANCE_STATUS_EXCUSED = "excused"

ATTENDANCE_STATUS_VALUES = {
    ATTENDANCE_STATUS_PRESENT,
    ATTENDANCE_STATUS_ABSENT,
    ATTENDANCE_STATUS_LATE,
    ATTENDANCE_STATUS_EXCUSED,
}
